### ISSUE TITLE
Not working with RN version 0.40

### ISSUE THREAD

**Issue by vexsnare** [devfd/react-native-workers#25]
`/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:7: error: cannot find symbol
import com.facebook.react.bridge.CatalystInstanceImpl;
                                ^
  symbol:   class CatalystInstanceImpl
  location: package com.facebook.react.bridge
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:8: error: cannot find symbol
import com.facebook.react.bridge.JSBundleLoader;
                                ^
  symbol:   class JSBundleLoader
  location: package com.facebook.react.bridge
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:9: error: cannot find symbol
import com.facebook.react.bridge.JSCJavaScriptExecutor;
                                ^
  symbol:   class JSCJavaScriptExecutor
  location: package com.facebook.react.bridge
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:10: error: cannot find symbol
import com.facebook.react.bridge.JavaScriptExecutor;
                                ^
  symbol:   class JavaScriptExecutor
  location: package com.facebook.react.bridge
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:15: error: cannot find symbol
import com.facebook.react.bridge.NativeModuleRegistry;
                                ^
  symbol:   class NativeModuleRegistry
  location: package com.facebook.react.bridge
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:28: error: cannot find symbol
    private JSBundleLoader jsBundleLoader;
            ^
  symbol:   class JSBundleLoader
  location: class ReactContextBuilder
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:37: error: cannot find symbol
    public ReactContextBuilder setJSBundleLoader(JSBundleLoader jsBundleLoader) {
                                                 ^
  symbol:   class JSBundleLoader
  location: class ReactContextBuilder
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:137: error: package NativeModuleRegistry does not exist
    private void addNativeModules(ReactApplicationContext reactContext, NativeModuleRegistry.Builder nativeRegistryBuilder) {
                                                                                            ^
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/WorkerModule.java:10: error: cannot find symbol
import com.facebook.react.bridge.JSBundleLoader;
                                ^
  symbol:   class JSBundleLoader
  location: package com.facebook.react.bridge
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/WorkerModule.java:168: error: cannot find symbol
    private JSBundleLoader createDevBundleLoader(String jsFileName, String jsFileSlug) {
            ^
  symbol:   class JSBundleLoader
  location: class WorkerModule
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/WorkerModule.java:178: error: cannot find symbol
    private JSBundleLoader createReleaseBundleLoader(String jsFileName, String jsFileSlug) {
            ^
  symbol:   class JSBundleLoader
  location: class WorkerModule
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:53: error: cannot find symbol
        JavaScriptExecutor jsExecutor = new JSCJavaScriptExecutor.Factory().create(new WritableNativeMap());
        ^
  symbol:   class JavaScriptExecutor
  location: class ReactContextBuilder
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:53: error: package JSCJavaScriptExecutor does not exist
        JavaScriptExecutor jsExecutor = new JSCJavaScriptExecutor.Factory().create(new WritableNativeMap());
                                                                 ^
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:62: error: package NativeModuleRegistry does not exist
        NativeModuleRegistry.Builder nativeRegistryBuilder = new NativeModuleRegistry.Builder();
                            ^
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:62: error: package NativeModuleRegistry does not exist
        NativeModuleRegistry.Builder nativeRegistryBuilder = new NativeModuleRegistry.Builder();
                                                                                     ^
/Users/vinay/git/sighte/node_modules/react-native-workers/android/src/main/java/co/apptailor/Worker/core/ReactContextBuilder.java:69: error: package CatalystInstanceImpl does not exist
        CatalystInstanceImpl.Builder catalystInstanceBuilder = new CatalystInstanceImpl.Builder()
                            ^`

**Comment by newhalo** [comment]
+1 .Same for me

**Comment by mmmurf** [comment]
Is this library being maintained?

**Comment by vexsnare** [comment]
No I guess.

**Comment by pbassut** [comment]
Same for me.

**Comment by osricwong** [comment]
same for me at RN v0.41.1

**Comment by danderson00** [comment]
There have been a bunch of breaking changes to the react-native Android libraries since the project was last updated. 

I just submitted a PR (https://github.com/devfd/react-native-workers/pull/26) to update to react-native@0.45.1. (Please note that I am not the project maintainer)

Please have a go at testing this update and leave any feedback in the PR.
